//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniDataEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEFINICAO
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public Nullable<int> ID_CAMPO { get; set; }
    
        public virtual CAMPO CAMPO { get; set; }
    }
}
