
CREATE TABLE CAMPO(
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY
	,NOME VARCHAR (50) NOT NULL
)

CREATE TABLE DEFINICAO(
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY
	,NOME VARCHAR (50) NOT NULL UNIQUE
	,ID_CAMPO INT FOREIGN KEY REFERENCES CAMPO(ID)
)

CREATE TABLE INDEXACAO_CAMPOS(
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY
	,ID_CAMPO INT NOT NULL FOREIGN KEY REFERENCES CAMPO(ID)
	,VALOR VARCHAR(MAX) NOT NULL
)

CREATE TABLE DOCUMENTO(
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY
	,ID_INDEXACAO_CAMPO INT FOREIGN KEY REFERENCES INDEXACAO_CAMPOS(ID)
)

CREATE TABLE TRABALHO(
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY
	,DATACRIACAO SMALLDATETIME NOT NULL
	,ID_DOCUMENTO INT NOT NULL FOREIGN KEY REFERENCES DOCUMENTO(ID)
)

/*
DROP TABLE TRABALHO
DROP TABLE DOCUMENTO
DROP TABLE INDEXACAO_CAMPOS
DROP TABLE DEFINICAO
DROP TABLE CAMPO
/*